base_model: AIDC-ai-business/Marcoroni-70B-v1
base_model_config: AIDC-ai-business/Marcoroni-70B-v1
model_type: LlamaForCausalLM
tokenizer_type: LlamaTokenizer
is_llama_derived_model: true

load_in_8bit: false
load_in_4bit: true
strict: false

datasets:
  - path: pharaouk/thinking-models
    type: alpaca
    
dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: ../n6/qlora-out

adapter: qlora
lora_model_dir:

sequence_len: 4096
sample_packing: true
pad_to_sequence_len: true

lora_r: 64
lora_alpha: 16
lora_dropout: 0.1
lora_target_modules:
lora_target_linear: true
lora_fan_in_fan_out:

wandb_project: 70B_thinker
wandb_entity:
wandb_watch:
wandb_run_id: 70B_thinker
wandb_log_model:

gradient_accumulation_steps: 4
micro_batch_size: 2
num_epochs: 3
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 50
eval_table_size:
save_steps: 50
hub_model_id: pharaouk/thinker-70B
bench_dataset: pharaouk/dharma-1/dharma_1_mini.json
do_bench_eval: true
save_total_limit: 5
debug:
deepspeed:
weight_decay: 0.0
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
tokens:
  - "<thinking>"
  - "</thinking>"
  - "<talking>"
  - "</talking>"
