base_model: mistralai/Mistral-7B-v0.1
base_model_config: mistralai/Mistral-7B-v0.1
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: Open-Orca/OpenOrca
    type: alpaca_w_system.load_open_orca
  - path: AlignmentLab-AI/agentcode
    type: oasst
  - path: garage-bAInd/Open-Platypus
    type: alpaca
  - path: glaiveai/glaive-code-assistant
    type: alpaca_chat.load_qa
  - path: pharaouk/cotC
    type: alpaca

dataset_prepared_path: last_run_prepared
val_set_size: 0.01
output_dir: ./out

sequence_len: 8192
sample_packing:
pad_to_sequence_len:

wandb_project: Mistral
wandb_entity: 
wandb_watch: 
wandb_run_id: mistral_full
wandb_log_model: "checkpoint"

gradient_accumulation_steps: 8
micro_batch_size: 4
num_epochs: 2
optimizer: adamw_bnb_8bit
lr_scheduler: cosine
learning_rate: 0.00006

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 250
eval_table_size: 5
hub_model_id: SkunkworksAI/Mistralic-7B
eval_table_max_new_tokens: 128
save_steps: 250
debug:
deepspeed:
weight_decay: 0.001
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"
