base_model: pharaouk/zeta-1B
base_model_config: pharaouk/zeta-1B
model_type: MixFormerSequentialForCausalLM
tokenizer_type: AutoTokenizer
is_llama_derived_model: false
trust_remote_code: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: Open-Orca/OpenOrca
    type: alpaca_w_system.load_open_orca
  - path: AlignmentLab-AI/agentcode
    type: oasst
  - path: garage-bAInd/Open-Platypus
    type: alpaca
  - path: glaiveai/glaive-code-assistant
    type: alpaca_chat.load_qa
  - path: pharaouk/cotC
    type: alpaca

dataset_prepared_path: last_run_prepared
val_set_size: 0.005
output_dir: ./phi-sft-zeta

sequence_len: 2048
sample_packing: true
pad_to_sequence_len: false

adapter:
lora_model_dir:
lora_r:
lora_alpha:
lora_dropout:
lora_target_linear:
lora_fan_in_fan_out:

wandb_project: zeta
wandb_entity:
wandb_watch:
wandb_run_id: zeta
wandb_log_model:

gradient_accumulation_steps: 16
micro_batch_size: 8
num_epochs: 2
optimizer: adamw_torch
adam_beta2: 0.95
adam_epsilon: 0.00001
max_grad_norm: 1.0
lr_scheduler: cosine
learning_rate: 0.0003

train_on_inputs: false
group_by_length: true
bf16: true
fp16: false
tf32: true

gradient_checkpointing:
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 1
xformers_attention:
flash_attention: true

warmup_steps: 100
eval_steps: 0.05
save_steps: 250
save_total_limit: 100
debug:
deepspeed:
weight_decay: 0.1
fsdp:
fsdp_config:
resize_token_embeddings_to_32x: true
special_tokens:
  bos_token: "<|endoftext|>"
  eos_token: "<|endoftext|>"
  unk_token: "<|endoftext|>"
  pad_token: "<|endoftext|>"
